### ISSUE TITLE
Error in marprobs[leftright_nodes_matrix[, 2], ] : subscript out of bounds

### ISSUE THREAD

**Issue by Menglinhsy** [nmatzke/BioGeoBEARS#4]
I have used BioGeoBears and followed the example successfully using DEC and DEC+J.
 
Both of the analysis ran smoothly, But I kept running into this error when I tried to plot the result_DEC, while DEC+J results can be plot successfully,
 
Here is the error:
 
“Error in marprobs[leftright_nodes_matrix[, 2], ] :
  subscript out of bounds”
 
Any advice would be very much appreciated! Thanks for your time and help.
 

[Distribution.txt](https://github.com/nmatzke/BioGeoBEARS/files/6347410/Distribution.txt)
[MadagascarTree.txt](https://github.com/nmatzke/BioGeoBEARS/files/6347412/MadagascarTree.txt)
[script.txt](https://github.com/nmatzke/BioGeoBEARS/files/6347414/script.txt)

**Comment by nmatzke** [comment]
Hi -- sorry for the slow reply. I think the issue was just that your script had

BioGeoBEARS_run_object$trfn = trfn
BioGeoBEARS_run_object$geogfn = geogfn
BioGeoBEARS_run_object = define_BioGeoBEARS_run()

...but it should be...

BioGeoBEARS_run_object = define_BioGeoBEARS_run() 
BioGeoBEARS_run_object$trfn = trfn
BioGeoBEARS_run_object$geogfn = geogfn

...because "BioGeoBEARS_run_object = define_BioGeoBEARS_run()" resets the run object to the default Psychotria shrub dataset.

I haven't run the whole long analysis, but that's probably it, script attached.

**Comment by nmatzke** [comment]
[script_v2.R.txt](https://github.com/nmatzke/BioGeoBEARS/files/6395573/script_v2.R.txt)
